#!/usr/bin/env python3
"""Macbook Pro 11.x brightness control

Usage:
    mbc start
    mbc screen (increase|decrease)
    mbc keyboard (increase|decrease)

"""

import socket
import sys
import os
import shutil
from docopt import docopt

BRIGHTNESS_SOCK = '/tmp/brightness_socket'
SCREEN_GMUX = '/sys/class/backlight/gmux_backlight/brightness'
KBD_SMC = '/sys/class/leds/smc::kbd_backlight/brightness'
UID = 'dmeulen'
GID = 'dmeulen'


def decode_msg(msg):
    msg_type, msg_cmd = msg.split(':')
    if msg_type == 'scr':
        screen_brightness(msg_cmd)
    if msg_type == 'kbd':
        kbd_brightness(msg_cmd)


def screen_brightness(cmd):
    current_brightness = open(SCREEN_GMUX).readline().rstrip()
    if cmd == '+':
        if int(current_brightness) >= 1000:
            return
        set_brightness = int(current_brightness) + 10
    elif cmd == '-':
        if int(current_brightness) <= 20:
            return
        set_brightness = int(current_brightness) - 10
    else:
        return
    with open(SCREEN_GMUX, 'w') as gmux:
        gmux.write(str(set_brightness))


def kbd_brightness(cmd):
    current_brightness = open(KBD_SMC).readline().rstrip()
    if cmd == '+':
        if int(current_brightness) >= 255:
            return
        set_brightness = int(current_brightness) + 5
    elif cmd == '-':
        if int(current_brightness) <= 0:
            return
        set_brightness = int(current_brightness) - 5
    else:
        return
    with open(KBD_SMC, 'w') as smc:
        smc.write(str(set_brightness))


def listener():
    try:
        os.unlink(BRIGHTNESS_SOCK)
    except OSError:
        if os.path.exists(BRIGHTNESS_SOCK):
            raise

    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    os.umask(0o027)
    sock.bind(BRIGHTNESS_SOCK)
    shutil.chown(BRIGHTNESS_SOCK, user=UID, group=GID)
    sock.listen(1)

    while True:
        connection, _ = sock.accept()
        try:
            while True:
                data = connection.recv(16)
                if data:
                    decode_msg(data.decode())
                else:
                    break
        finally:
            connection.close()


def send_cmd(msg):
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        sock.connect(BRIGHTNESS_SOCK)
    except:
        print('Could not connect to socket')
        sys.exit(1)

    sock.sendall(msg)
    sock.close()


if __name__ == '__main__':
    ARGS = docopt(__doc__)
    if ARGS['start']:
        listener()
    if ARGS['screen']:
        if ARGS['increase']:
            send_cmd(b'scr:+')
        if ARGS['decrease']:
            send_cmd(b'scr:-')
    if ARGS['keyboard']:
        if ARGS['increase']:
            send_cmd(b'kbd:+')
        if ARGS['decrease']:
            send_cmd(b'kbd:-')
